### PR TITLE
removed previous db_schema and replaced them with an up to date one

### PR DESCRIPTION
**Pull request by JonathanMary**
Previous two files were outdated and not the actual database. The new db_schema is what labs33 ended with.

 - [x] a clear rationale for the feature (user story)
 - [/] a screen shot showing either the intended state or completed state of the feature
 - [x] additional context about changes made in the PR 

# Atomic, well named commits
 - [x] name is specific to feature changes or additions
 - [x] commits have descriptive messages regarding what changed in the code

# Appropriately scoped  
- [x] focused on a single problem
- [x] small enough/ easy to review

# Adequately reviewed
- [x] sent to multiple reviewers
- [x] reviewed by at least two people
- [x] cross team review if necessary 
- [x] ensure there is at least one piece of feedback from each reviewer

# Code is clear and maintainable
- [x] consistently formatted
- [x] has config files to enforce linting and formatting
- [x] NO LOGS OR PRINT STATEMENTS
- [x] code is idiomatic/best practice  

- [x] No failing unit test

### CODE REVIEW

**Review by dgamboa — CHANGES_REQUESTED** [review]
@JonathanMary it looks like there is an extra line on the newCaseRouter file and GitHub raised a flag for it. Can you check that out before merging the changes?

**Comment by dgamboa** [comment]
The updated schema picture looks great. In particular, the notes re: the cases table and the judges table -- especially the flag of outstanding work on the judges model -- add a lot of context to the project docs. Thanks for taking care of this.

**Comment by sebastian-espeset** [comment]
Thanks for updating this, looks good

**Review by nwestallen — APPROVED** [review]
New db schema looks good and I approve pending Daniel's requested fix.

**Review by sebastian-espeset — APPROVED** [review]
Looks good!

**Pull request merged**
